pipeline:

    test_build:
      image: docker:18.09
      environment:
        - DOCKER_HOST=tcp://172.17.0.1:2375
      commands:
        - docker build -t registry.fastdns.io/drone/test .
      when:
        event: push